#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="${ROOT_DIR}/demo_outputs/latest"
PYTHON_BIN="${PYTHON_BIN:-}"

if [[ -z "${PYTHON_BIN}" ]]; then
  if [[ ! -x "${ROOT_DIR}/.venv/bin/python" ]]; then
    echo "No local .venv found. Running setup first..."
    bash "${ROOT_DIR}/setup.sh"
  fi
  PYTHON_BIN="${ROOT_DIR}/.venv/bin/python"
fi

echo "Running CampaignForge AI demo..."
echo "Using Python: ${PYTHON_BIN}"

mkdir -p "${OUTPUT_DIR}"

pushd "${ROOT_DIR}" >/dev/null

"${PYTHON_BIN}" etl/marketing_etl.py
"${PYTHON_BIN}" models/train_model.py
"${PYTHON_BIN}" models/evaluate_model.py
DEMO_OUTPUT="$("${PYTHON_BIN}" -m genai.demo --input data/demo/campaign_brief.json)"
printf '%s\n' "${DEMO_OUTPUT}"
CAMPAIGN_ID="$(printf '%s\n' "${DEMO_OUTPUT}" | awk -F': ' '/Generated campaign brief output:/ {print $2}' | tail -n 1)"
if [[ -z "${CAMPAIGN_ID}" ]]; then
  echo "Could not identify generated campaign id from demo output." >&2
  exit 1
fi
"${PYTHON_BIN}" -m genai.image_demo --campaign-id "${CAMPAIGN_ID}"
"${PYTHON_BIN}" -m genai.export_demo --campaign-id "${CAMPAIGN_ID}"

LATEST_MODEL="$(ls -1t models/artifacts/models/trained_model_*.pkl | head -n 1)"
LATEST_TRAIN_METRICS="$(ls -1t models/artifacts/models/trained_model_*_metrics.json | head -n 1)"
LATEST_EVAL_METRICS="$(ls -1t models/outputs/*_evaluation.json | head -n 1)"
LATEST_GENAI_IMAGE_DIR="data/generated/assets/images/${CAMPAIGN_ID}"
LATEST_GENAI_EXPORT="data/generated/assets/exports/${CAMPAIGN_ID}.zip"
LATEST_GENAI_DATABASE="data/generated/metadata/campaigns.sqlite3"

cp "${LATEST_MODEL}" "${OUTPUT_DIR}/"
cp "${LATEST_TRAIN_METRICS}" "${OUTPUT_DIR}/"
cp "${LATEST_EVAL_METRICS}" "${OUTPUT_DIR}/"
mkdir -p "${OUTPUT_DIR}/genai"
cp "${LATEST_GENAI_EXPORT}" "${OUTPUT_DIR}/genai/"
cp "${LATEST_GENAI_DATABASE}" "${OUTPUT_DIR}/genai/"
printf '%s\n' "${DEMO_OUTPUT}" > "${OUTPUT_DIR}/genai/demo-output.txt"
mkdir -p "${OUTPUT_DIR}/genai/images"
find "${LATEST_GENAI_IMAGE_DIR}" -maxdepth 1 \( -name '*.svg' -o -name '*.png' \) -exec cp {} "${OUTPUT_DIR}/genai/images/" \;

cat > "${OUTPUT_DIR}/README.txt" <<EOF
CampaignForge AI Demo Output

Generated by: run-demo.sh

Included files:
- $(basename "${LATEST_MODEL}")                latest trained model artifact
- $(basename "${LATEST_TRAIN_METRICS}")        training metrics saved during model training
- $(basename "${LATEST_EVAL_METRICS}")         evaluation metrics for the latest model
- genai/demo-output.txt                         generated campaign id and logical record references
- genai/$(basename "${LATEST_GENAI_DATABASE}")  SQLite campaign metadata store snapshot
- genai/images/*                                saved concept image assets
- genai/$(basename "${LATEST_GENAI_EXPORT}")    exported campaign ZIP bundle

Recommended next steps:
1. Inspect the JSON metrics files in this folder.
2. Inspect the generated campaign brief outputs in the genai/ folder.
3. Inspect the saved image concepts in the genai/images/ folder.
4. Download or inspect the exported campaign ZIP in the genai/ folder.
5. Run 'make api' to launch the FastAPI demo.
6. Run 'make dashboard' to launch the Streamlit demo.
EOF

popd >/dev/null

echo
echo "Demo complete."
echo "Demo outputs written to: ${OUTPUT_DIR}"
